### ISSUE TITLE
Help-How To Set font.familyname , font.fullname, font.fontname at Some Lanaguge

### ISSUE THREAD

**Issue by life888888** [HinTak/freetype-py#2]
I modify cjk-multi-fix.py to ttf-rename.py
[ttf-rename.zip](https://github.com/HinTak/freetype-py/files/9735296/ttf-rename.zip)

and run this command 
```
$ fontforge -script ttf-rename.py NotoSansCJKtc-BoldItalic.ttf NotoSansCJKtc-BoldItalic_NEW.ttf \
  "Noto Sans CJK TC" "Noto Sans CJK TC Bold Italic" "NotoSansCJKTC-BoldItalic"

```

![2022-10-07 23-46-42](https://user-images.githubusercontent.com/101442875/194595357-34d8f537-b073-422c-9604-44bce4f78a21.png)

I can change English Language Styles and Fullname.
But I can not change Chinese Language Styles and Fullname.

Would you please, help me, tell me how to set Chinese Language Styles and Fullname ???

**Comment by HinTak** [comment]
That's a question on how to use fontforge (and its python scripting extension).
